import Anthropic from '@anthropic-ai/sdk';
import type { EncounterLogLine } from './sessions.js';

export interface EncounterRecord {
  id: string;
  timestamp: string;
  description: string;
  encounterTitle: string;
  xpGained: number;
  goldGained: number;
  outcome: 'survived' | 'defeated';
  lines: EncounterLogLine[];
}

export interface StorylogEntry {
  encounterId: string;
  narrative: string;
}

const SYSTEM_PROMPT = `You are a fantasy novelist writing a single encounter entry for an adventurer's story log.

You will receive the scene description and the sequence of events from one encounter. The events are a literal record of what happened — your job is to narrate them as prose, NOT to embellish them with content the player did not produce.

GROUNDING (absolute):
- Narrate ONLY actions, choices, gestures, and outcomes that appear in the events transcript.
- Player dialogue may appear in your output ONLY if it was sent by the player (lines marked "[player]" in the transcript). Do NOT invent quips, taunts, or one-liners for the player or their character. If the player did not speak, the player does not speak in the narrative.
- NPC dialogue may appear in your output ONLY if it was generated by the dungeon master (lines marked "[dungeon master]"). Quote naturally, paraphrase where helpful, but do not invent fresh NPC lines.
- Do not add gestures, glances, or beats ("she smirked", "with a nod", "winked at the traveller") that aren't grounded in events. The reader of the story log expects an accurate recap, not creative writing on top of one.
- If the encounter contained no dialogue at all, include none in your narrative.

STYLE:
- Write exactly one short paragraph of two to three sentences. Third person. Past tense.
- Weave the scene description naturally into the narrative — do not quote or restate it directly.
- Wrap quoted dialogue (when present in the transcript) in italics with *asterisks*.
- Never mention dice rolls, HP numbers, damage numbers, skill names, XP amounts, or gold amounts.
- Translate mechanical events into narrative: a hit is a blow landed, a kill is a death, Second Wind is finding a reserve of strength. Match the weapon ("Hit with Shortbow" → "an arrow flew", "Hit with Greatsword" → "the blade fell").
- Write as if narrating a fantasy novel, not logging a game session.
- Do not include headers, titles, or separators — output only the prose.`;

function buildPrompt(record: EncounterRecord): string {
  const events = record.lines.map((l) => {
    if (l.type === 'dm_player') return `  [player] ${l.text}`;
    if (l.type === 'dm_reply') return `  [dungeon master] ${l.text}`;
    return `  [event] ${l.text}`;
  }).join('\n');
  return `Scene: ${record.description}\n\nEvents:\n${events}`;
}

export async function generateStorylog(
  anthropic: Anthropic,
  encounterLog: EncounterRecord[],
  existing: StorylogEntry[],
  rewrite: boolean,
): Promise<StorylogEntry[]> {
  const base = rewrite ? [] : existing;
  const doneIds = new Set(base.map((e) => e.encounterId));
  const toGenerate = [...encounterLog].reverse().filter((r) => !doneIds.has(r.id));

  const newEntries: StorylogEntry[] = [];
  for (const record of toGenerate) {
    const res = await anthropic.messages.create({
      model: 'claude-sonnet-4-6',
      max_tokens: 400,
      system: SYSTEM_PROMPT,
      messages: [{ role: 'user', content: buildPrompt(record) }],
    });
    const narrative = res.content.find((b) => b.type === 'text')?.text?.trim() ?? '';
    newEntries.push({ encounterId: record.id, narrative });
  }

  return [...base, ...newEntries];
}
